version: "3.9"

# =====================================
# GeoVision3D Docker Compose
# =====================================

services:

  geovision3d:

    container_name: geovision3d

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      PORT: 8080
      ENVIRONMENT: production

    volumes:
      - ./static:/root/static

    networks:
      - geovision-network

# =====================================
# NETWORKS
# =====================================

networks:

  geovision-network:
    driver: bridge
